// Code generated by spansloc. DO NOT EDIT.
package main

import (
	"gopkg.in/DataDog/dd-trace-go.v1/ddtrace/tracer"
	"log"
)

func init() {
	log.Print("init register locations for main")
	tracer.RegisterSpansLocations(
		tracer.SpanLoc{"main", "/Users/jeanbaptiste.pinalie/go/src/github.com/jybp/dd-hackathon-2021-v2/cmd/main.go", 20},
	)
}
