// Code generated by spansloc. DO NOT EDIT.
package pkg

import (
	"gopkg.in/DataDog/dd-trace-go.v1/ddtrace/tracer"
	"log"
)

func init() {
	log.Print("init register locations for pkg")
	tracer.RegisterSpansLocations(
		tracer.SpanLoc{"hello", "/Users/jeanbaptiste.pinalie/go/src/github.com/jybp/dd-hackathon-2021-v2/pkg/pkg.go", 12},
	)
}
